### ISSUE TITLE
Implement basic Parser

### ISSUE THREAD

**Issue by rengolin** [microsoft/verona#103]
With the token tree in hand, produce an AST from it. If writing it in opaque MLIR is a good idea (see #101), then output opaque MLIR in a recognisable shape.

Acceptance criteria:
 * Can parse the existing Verona examples (write more examples if necessary)
 * Can dump the AST in text form
 * Has tests that show the expected AST from given source
 * Test coverage is 100% of what's exposed in existing examples

Not included:
 * Support for the full language
 * Type inference, validation
 * MLIR lowering

**Comment by rengolin** [comment]
@plietar I think we should reuse, or at least heavily borrow from your prototype.

**Comment by davidchisnall** [comment]
The prototype uses Pegmatites, which is designed for teaching and for rapid prototyping.  We should not aim to reuse any of the Pegmatite code for a production compiler.

**Comment by mjp41** [comment]
@sylvanc has a prototype parser in a private repo he was working on that might be a useful starting point.  

The current parser has some quirks, that I don't think need replicating. It tries to accept a mix of ML like syntax, and only requires parenthesis where necessary

```ML
   if true {..} else {..}
```
versus
```C++
   if (true) {..} else {..}
```
I think we should just enforce parens as it makes the syntax more regular.

**Comment by rengolin** [comment]
I agree. Fuzzy syntax creates complications for the compiler for no additional benefits to the user. We may want to re-think this later, by adding syntactic sugar to the language (and its own parsing rules), but that has to be a _conscious_ act for real benefit, not premature laziness.

**Comment by rengolin** [comment]
Superseeded by #111
