### ISSUE TITLE
Add LLVM/MLIR build in GitHub CI

### ISSUE THREAD

**Issue by rengolin** [microsoft/verona#110]
We'll soon need LLVM/MLIR src/build dir, and GitHub can cache build dirs of specific builds, we need to set that up and keep it current for all other Verona's CI builds.

**Comment by rengolin** [comment]
@SeanTAllen, as our in-house expert, whenever you have some time, can you have a look at this one?

**Comment by SeanTAllen** [comment]
We had a side conversation about this. You can't build LLVM directly on GitHub actions. It will choke. Renato is looking into getting appropriate Azure runners that could be used from GH.

**Comment by rengolin** [comment]
I'll let you know when we have the subscription, so we can start creating the builders and connecting them to the CI.

**Comment by rengolin** [comment]
PRs #162 and #155 implement this issue.

**Comment by rengolin** [comment]
With #162 done, #155 changes are only towards LLVM using it, so I'll mark this as closed (singe LLVM build is already on master).
