### ISSUE TITLE
Merge Sylvan's parser into Verona

### ISSUE THREAD

**Issue by rengolin** [microsoft/verona#111]
@sylvanc has a parser in a local repo that can parse Verona. It has a PEG definition that is flexible and the code is reasonably straightforward, both which are great for early prototyping. We should merge this in the `src` directory and use the generated AST to start lowering MLIR.

We may want to build a robust parser later, with @davidchisnall's recommendations in #102, but that'll be for another ticket.

**Comment by mjp41** [comment]
Closed by #116
