### ISSUE TITLE
Better error message on ctest failure

### ISSUE THREAD

**Issue by rengolin** [microsoft/verona#114]
I tried to build Verona today and _all_ tests failed on master, which doesn't make sense.

When running `ctest -R <test> -V` I noticed the error was:
```
9: CMake Error at .../verona/testsuite/common.cmake:11 (message):
9:    To run tests you must build the install target.
```

It's not a widespread practice to require `ninja install` before testing, but it's not uncommon either. 

The best "fix" would be to create a `ninja check` which depends on `install` and just runs `ctest`. 

Another option would be to not require installing and take the binaries and libraries from the build directory.

**Comment by plietar** [comment]
> Another option would be to not require installing and take the binaries and libraries from the build directory.

The reason we didn’t do this is because the compiler expects the builtin.verona file to be at a specific place relative to the compiler executable, which isn’t true before installing. Obviously there are other ways to work around that problem.

**Comment by mjp41** [comment]
The msbuild builds have different configurations in a single build directory, which ninja and Makefiles don't.  Coping with the different layouts is annoying, and install does that for you.  This makes testing much easier.  I am happy to take a cleaner solution that also works with msbuild.

**Comment by rengolin** [comment]
On Windows, I can't add the dependency from `check` to `install` because the target `install` doesn't exist. How does one install on Windows, then? Maybe it's a different name for the target?

I don't mind fixing (or not) the install later, but it would be good to have a sensible testing target, so we don't need to write a lot of documentation around testing and just say `ninja check`.

**Comment by mjp41** [comment]
I think we might have to reflect the install target into cmake as a custom command, I am just experimenting at the moment.  I am thinking something like
```
add_custom_target(install_for_test
   COMMAND cmake --build $(CMAKE_BINARY_DIR) --config $(CMAKE_BUILD_TYPE) --target install
```
