### ISSUE TITLE
Will there be support for a C FFI

### ISSUE THREAD

**Issue by Nate-Watts** [microsoft/verona#130]
FAQ: "One of our core aims with Project Verona is to support high-quality C++ FFI. To support this, we will need extremely tight integration with a C++ compiler, like Clang. Using C++ as the implementation language of our compiler makes this integration much simpler."

Does this imply that support for a C FFI will come hand-in-hand with the C++ FFI or is support strictly C++ only?

**Comment by davidchisnall** [comment]
From an ABI perspective (which is what we care about for interop), C is a subset of C++. If we support C++, we trivially support C.

Modern C++ libraries provide memory-safe interfaces, expressed in terms of smart pointers, iterations, and so on. We don’t want to lose this when invoking the code from Verona: even if our goal is that all C++ code should be sandboxed, we shouldn’t require interop code that increases the chance of bugs that can lead to sandbox compromise. A lot of existing interop layers for safe languages require wrapping your type-safe C++ APIs in C code full of void pointers and unsafe casts. We view this as completely unacceptable for a safe language.

**Comment by Nate-Watts** [comment]
Cool. That answers my question. Thanks!
