### ISSUE TITLE
GCC built runtime tests fail with corruption

### ISSUE THREAD

**Issue by rengolin** [microsoft/verona#165]
After cleaning up for warnings (#164), the GCC build still fails. The following tests crash:
	  7 - func-con-ext_ref (Child aborted)
	 11 - func-con-finalisers (Child aborted)
	 14 - func-con-memory (Child aborted)
	 25 - perf-con-linkedlist (Child aborted)

This has been present since the first commit, so not a "regression" per se, but a bug nonetheless. With the tests broken, we'll have to disable the GCC build on the CI, which is a bad thing.

Fixing this problem while we're still fresh would be better than leaving this to hang for months and then deciding to never build with GCC any more.

@theodus @mjp41

**Comment by rengolin** [comment]
I'm using GCC 10.1 on Arch and I cannot make it fail... :/

**Comment by Theodus** [comment]
Have you tried with `-DRT_TESTS=ON`?

**Comment by rengolin** [comment]
yeah:
```
verona/build$ cmake .. -GNinja -DRT_TESTS=On -DEXTRA_VERONA_CMAKE_FLAGS="-DCMAKE_C_COMPILER=gcc;-DCMAKE_CXX_COMPILER=g++;-DCMAKE_CXX_FLAGS=-stdlib=libstdc++"
verona/build$ ninja
verona/build/verona-prefix/src/verona-build$ ctest -j 32 -R -con-
```

**Comment by rengolin** [comment]
@theodus, I thought you had fixed the build error, but left the runtime test error.

A recent [nightly build](https://dev.azure.com/ProjectVeronaCI/Project%20Verona/_build/results?buildId=1286&view=logs&j=58c83696-1038-5e38-29b3-1a10c75b2938&t=ea4bd8d5-ac33-5318-3408-4424411dc055&l=280) still shows build errors.

That build uses GCC 7.5.

**Comment by Theodus** [comment]
Those changes were never merged, since the CI could never pass
