### ISSUE TITLE
Build LLVM on same path as Verona

### ISSUE THREAD

**Issue by rengolin** [microsoft/verona#169]
The LLVM build happens on a different type of machine, so the disk, path and libraries available are completely different. This may cause library version problems in the future, but right now, it's causing path problems.

LLVM's build creates CMake files in the build directory like MLIRConfig and LLVMConfig. Standalone dialects use those files to find the libraries, headers and tools needed to build themselves, but they have hard-coded paths (with the original LLVM build ones).

For now, we added a hack that replaces all original build paths with Verona's location (`external/llvm-project/build`) using a perl inline replace command for all CMake files. This is ugly.

The idea is to use the same machine type to build both LLVM and Verona, but that means either using a slow machine to build LLVM, or a fast and expensive machine to build Verona. We need to pick one that makes sense long term and then remove the path replacement part in the current CI.

**Comment by mjp41** [comment]
The install directory from #187 fixes this problem, implemented in #198.
