### ISSUE TITLE
CMake magic for building LLVM if not cached

### ISSUE THREAD

**Issue by rengolin** [microsoft/verona#190]
On CI and local development machines, most of us use the cached version of LLVM, following the building instructions. But sometimes we want to build our own LLVM. And it would be nice to not have to do that as a separate step than "cmake/ninja" on Verona's build directory. This would also make it less surprising when users try to do just that without reading the docs.

It would be nice to have some CMake magic that detects if the LLVM build directory exists and has the appropriate tools (ex. `mlir-tblgen`). If it doesn't exist, add a task to build LLVM in the submodule directory as part of the requirements.

**Comment by mjp41** [comment]
I was just thinking about doing this.  So I'll take a first stab.

**Comment by rengolin** [comment]
Closed by #197
