### ISSUE TITLE
setup-llvm-builddir.sh fails silently when using the wrong filename

### ISSUE THREAD

**Issue by plietar** [microsoft/verona#194]
I accidentally omitted the OS name from the argument of `setup-llvm-builddir.sh`, which made the invocation of `wget` fail and the script exit. However it didn't print any error message, leading me to think everything worked.

What's worse is an empty `tar.gz` file was still created, so running the script again tried to extract it, leading to confusing failures when `find "$llvm_root/build"` failed.

**Comment by mjp41** [comment]
I am hopefully deleting that script today.  I will submit a PR ASAP

**Comment by mjp41** [comment]
Removed by #198
