### ISSUE TITLE
Github - Devops integration broken, tests running but action not informed

### ISSUE THREAD

**Issue by rengolin** [microsoft/verona#210]
Pull requests can't be merged without all tests passing. The tests are running on Devops pipelines, but Github actions are not being notified and the PR can't be merged.

There must be something wrong with the triggers, I'll clean up and try again from scratch. Hopefully this will fix issues.

**Comment by rengolin** [comment]
Deleted and recreated the branch protection rules, no difference.

**Comment by rengolin** [comment]
Examples:
 * https://github.com/microsoft/verona/pull/209 -> https://dev.azure.com/ProjectVeronaCI/Project%20Verona/_build/results?buildId=1308&view=results
 * https://github.com/microsoft/verona/pull/211 -> https://dev.azure.com/ProjectVeronaCI/Project%20Verona/_build/results?buildId=1310&view=results

**Comment by rengolin** [comment]
Forced "Pull request validation" trigger on Pipeline job (override yaml settings), no difference.

**Comment by rengolin** [comment]
Seems to be broken to other projects as well, so not specific to our repo, at least.

**Comment by rengolin** [comment]
Started with #202 (https://dev.azure.com/ProjectVeronaCI/Project%20Verona/_build/results?buildId=1296, https://dev.azure.com/ProjectVeronaCI/Project%20Verona/_build/results?buildId=1298, https://dev.azure.com/ProjectVeronaCI/Project%20Verona/_build/results?buildId=1299).

It was closed to try again, #207 (https://dev.azure.com/ProjectVeronaCI/Project%20Verona/_build/results?buildId=1301, https://dev.azure.com/ProjectVeronaCI/Project%20Verona/_build/results?buildId=1304, https://dev.azure.com/ProjectVeronaCI/Project%20Verona/_build/results?buildId=1306)

Then I created the test PR (described above). All PRs triggered tests, all passed, none were reported back to GitHub.

**Comment by plietar** [comment]
Seems like it's working again:
https://github.com/microsoft/verona/pull/214 is green and mergeable
https://github.com/microsoft/verona/pull/206 is (at the time of writing) pending, but there's a link to CI.

I just had to amend and force push to cause a rebuild on #206.

**Comment by rengolin** [comment]
Awesome! They must have fixed whatever was broken. I have submitted a bug report in Azure, but got no reply whatsoever. I don't think I was the only one, though, so it's ok.

**Comment by plietar** [comment]
Funnily enough, #206 is now stuck in the same way waiting for the CLA bot.
