### ISSUE TITLE
Create a language ABI handler

### ISSUE THREAD

**Issue by rengolin** [microsoft/verona#259]
The language has some behaviour that needs a common place to live. The first example is `for`'s handling for iterative types (`has_value`, `apply`, `next`) in #256. Other examples will be that lambdas, constants, when blocks will need special anonymous objects with pre-defined shape, which the lowering needs to know how to lower both sides,

Another option would be to do that at the AST level (like current empty function names are converted to `apply`), and just let the MLIR lowering be as dumb as possible in regards to ABI.

We need to discuss how this will be implemented and at which level (AST, MLIR).

**Comment by rengolin** [comment]
One of the problems raised in #261 is that ABI/Lowering handlers don't know where they're implemented. 

If they're implemented by the *compiler*, we need to define (not just declare) the function directly into the module.

If they're implemented by the *library*, we need do declare them in a header that is always included and make sure linking finds the runtime library.

If they're implemented by the *user*, we don't need to do anything and should just rely on the user having done the right thing, and erroring out if they didn't.

The ABI/Lowering handlers must do the right thing, independent of how it's implemented.

**Comment by davidchisnall** [comment]
I think there are a few things conflated here that we might want to track separately:

 - Desugaring-style lowerings (e.g. expanding closures to objects with an `apply` method, calling `apply` for function-like invocations), where we're not locally defining the binary layout, but we are defining the equivalence of two source-level constructs.  These will be 100% shared between all targets.
 - Traditional ABI concerns, such as the layout of vtables (with selector colouring), packing of structures, and so on, which may vary between targets (some may be mostly generic, but depend on things like the representation of a pointer / virtual address for the target).
 - Contracts between the language and user code, such as how iteration loops get the range, how string literals turn into a concrete type, and so on (personally, I'd like as many of these as possible to be entirely library constructs, but that depends on sufficient source-level reflection working that we can implement for-in loops the standard library).
 - Contracts between the language and the standard library, in the form of built-in types and functions that are used to implement things that can't be expressed in Verona.

There are some overlaps between them but it's probably good to consider them separately.

**Comment by rengolin** [comment]
Some de-sugaring happens at the AST level, for instance, replacing empty functions with `apply`. Some de-sugaring doesn't, for example, the `for` loop. We need to agree on what happens where. Without evidence, I think we should do **all** de-sugaring at the AST level. Happy to be proven wrong, but I'd like to treat the corner cases as special cases, not the rule.

Traditional ABI concerns (like structure layout, etc) should be done by the MLIR layer. The AST simply has no concept of "memory". Those will need structures and functions to be created by the compiler or implemented in the runtime library (or both), which means the MLIR layer should either pepper the code with helper functions and structures as needed or know which helper functions to call and structures to use. Either way, we need that knowledge in the compiler and in sync with the runtime implementation.

Interactions between user code and the language must be controlled by well defined, user-visible "headers" (whatever that means). It must have visible interfaces that the user can override and cause errors if ill created, well before execution. It needs to change with the times (official standard iterations), it can allow different (target-specific) logic to co-exist, etc. The headers can be a document that the compiler is guaranteed to conform to, or an actual module that gets included on all compilation units, doesn't matter, as long as we can check syntax and semantics at compile time.

This "issue" is an attempt to discuss all those ideas, and to split into sub-issues when we have more consensus for each idea.

**Comment by rengolin** [comment]
This is a catch-all issue that was more about the discussion than implementation. On the two issues this raises, #272 discusses the ABI and #271 the de-sugaring of `for` loops. We should track their progress there, so I'll close this one.
