### ISSUE TITLE
Function table matches

### ISSUE THREAD

**Issue by rengolin** [microsoft/verona#264]
As exposed in #261, looking up functions in the symbol table only looks at the function name, not its signature. This was meant to simplify the implementation at such an early stage, but we'll begin to run into problems soon, so we should fix this. There are two ways I imagine this could be fixed.

First, we could use mandatory *name mangling* for all functions. This would make it really easy to find the signature if the types are simple, but not if there are type intersections. For example:
```
foo(imm) -> U32;
foo(S32 | iso) -> U32;

bar(a : S32 | imm) -> U32 {
  return foo(a);
}
```
Mangling all variations and searching for it in the symbol table won't scale.

Second, we could specialise the function table to check for types (args, ret) in addition to names. This would only work *after* finding all functions with the same name and number of arguments, which can considerably restrict the problem space. But it means specialising the function table over all other symbol tables.

There may be better ways, though.

**Comment by rengolin** [comment]
If we allow for default arguments, then the "number of arguments" check would be a little harder.

We could create multiple versions in the symbol table with varying number of arguments, for example, to make that simpler.

**Comment by davidchisnall** [comment]
I believe that we were intending to not support overloading, so we need to look up only on function name and number of arguments (`foo/1` and `foo/2` are different, `foo(imm & T)` and `foo(iso & T)` may not exist in the same scope), so we don't need to hold both in the symbol table, we just need to note the conflict and raise an error.  @sylvanc, does that correspond with your understanding?

**Comment by rengolin** [comment]
This sounds very restrictive... A common pattern this breaks is:
```
add(float, float) -> float
add(int, int) -> int
add(complex, complex) -> complex
```
So that we can use `add` in a template class for all those types, like:
```
class Foo[T] {
  add(a:T, b:T) -> T {
    return ::add(a, b);
  }
}
```

**Comment by rengolin** [comment]
Turns out, this is a lot simpler than we thought.

First, function resolution based on types is undecidable. C++ does it is by having a nightmare of rules and match ordering, implementing constructors and operators, etc. Not worth it. (phew!)

Second, matching "foo/1" doesn't help with partial application, ex. `foo(a) { foo(a, 42) }`.

Third, functions have context from their arguments already (the first argument is special, as it defines the operation). For example, `a+b` is the same as `a.+(b)`, and if a is `U32`, then it's the same as `U32.+(a, b)`. The overload case above is resolved by that feature.

Fourth, functions live inside wider contexts. Classes, modules, etc. add "namespace" to the functions' names, for example `Foo.U32.+(a, b)` could be different than `Bar.U32.+(a, b)`, and as long as the naming resolution is unambiguous (including type alias, module names and aliases, etc.), there is no risk of calling the wrong function.

This means that:
1. We should not include arguments or types in the symbol table
2. We don't need to mangle the number of arguments onto the function's name
3. We must get the name resolution unambiguously (to be defined and implemented).

The third point there is still not clear when it should happen. Do we store the unambiguous name in the symbol table? Or do we store only the function name, and build the rest of the name scope from the surrounding context?

The answer to that question will certainly depend on how much information we get from the AST. If it's guaranteed that we'll always have the full context for every function declaration and that we will always declare all functions before calling them, than the former is preferred. If not, then the latter is the only solution.

**Comment by rengolin** [comment]
I'll drop the current implementation of argument-based function name resolution and will close this issue for now.

Once we get to the point where we're implementing classes and modules, we'll have to look into name resolution anyway, so no need to create an issue right now for that.
