### ISSUE TITLE
interpreter and compiler binaries only build on make check

### ISSUE THREAD

**Issue by rengolin** [microsoft/verona#265]
I'm not sure why, but on the CI builds those binaries only build on the "Check" task, not on "Build".

It's not critical that it does, but I wonder if the default target should also include those sub-projects?

If that's intentional, then we can close this bug.

**Comment by mjp41** [comment]
It is not intentional.  I thought they should be built on the top-level default.

**Comment by mjp41** [comment]
Is it that they aren't built, or aren't installed in the dist directory?  It could be the separation of the test task, has removed the install task in that instance.

**Comment by rengolin** [comment]
They aren't built. Could be that the install doesn't exist, then they're not built. But the tests need them, so they're built before it.

**Comment by rengolin** [comment]
Ok, removed the question, we should eventually "fix" this, though it isn't important.

**Comment by rengolin** [comment]
I have merged this with #198, so that we don't proliferate CI issues.

**Comment by mjp41** [comment]
For me 
```
ninja
```
Builds and installs the interpreter, etc.
```
ninja check
```
Reinstalls the interpreter, but does not rebuild it.  Could you give a few more details of the configuration.

**Comment by rengolin** [comment]
This is the `Verona CI` build.

You are right that `ninja` builds both (I hadn't noticed), but in the CI, `ninja check` builds again, ex: https://dev.azure.com/ProjectVeronaCI/Project%20Verona/_build/results?buildId=1492&view=results
