### ISSUE TITLE
De-sugar at AST level

### ISSUE THREAD

**Issue by rengolin** [microsoft/verona#271]
As discussed in #259, we need to define what will be de-sugared at the AST level and what will be assumed by the MLIR layer to perform.

My personal opinion is that **all** mechanical de-sugaring should be done by the AST, before getting to MLIR. For example, we already have empty functions renamed to `apply`. But we don't have `for` loops converted to their respective `while` counterparts. Because these are both purely mechanical, the AST should do both.

Another issue is class method versus static methods. Currently, methods without a `self` argument are considered static, but the current design is to add a mandatory `static` keyword, too. With that, we could omit the `self` argument and assume it's always passes on non-static methods (like C++, Java). If we do that, then it would be up to the AST to add the `self` argument to all non-static methods.

There's also _native_ instructions. We consider `a : U32 + b : U32` equivalent to `a.+(b : U32) : U32` and to `U32.+(a : U32, b : U32)` and the same set with `add` instead of `+`. Currently, the AST doesn't discern between the first two, but there's no `U32` static version of it that I know. If we want to consider all of them a machine instruction `add`, we should lower them all to the same instruction, in which case it would be great if they appear in the AST as the same pattern.

Finally, there's name mangling. We have classes and methods and to make sure we call the right ones, we'll need to mangle the names for the final call like `ClassName.MethodName.SomeTypeInfo()`. Currently, the AST has enough information as is to let the MLIR layer mangle the names (methods are inside classes and have most types explicit), but that means the MLIR layer will have to _know_ what the convention is and strictly follow it to conform to library calls, external code, user overridden methods, etc. If the AST does any of that already, it would be advisable to keep that logic all in one place, or high maintenance costs can lead to silent codegen failures.

I'm sure I'm forgetting a lot of things, feel free to add issues here to handle. We need to discuss the topics, and that's the point of this issue. Individual issues should be created to handle each case we decide here.

**Comment by mjp41** [comment]
So 

> Another issue is class method versus static methods. Currently, methods without a self argument are considered static, but the current design is to add a mandatory static keyword, too. With that, we could omit the self argument and assume it's always passes on non-static methods (like C++, Java). If we do that, then it would be up to the AST to add the self argument to all non-static methods.

We want to specify information about the type of `self`, e.g. `imm`, `mut`, `iso`.  I think we always want an explicit `self`, and moreover, it doesn't have to be called `self`, so that certain nesting of things work.

**Comment by mjp41** [comment]
Generally, I agree with removing syntactic sugar as soon as possible.

My main concern is when type inference fires, versus concretizing certain patterns.  If any sugar is resolved using type information then it will need removing in MLIR.  Currently, I don't think we have a need for this, but just want to raise it, in case anyone else can think why we might want ot.

**Comment by davidchisnall** [comment]
I agree with @mjp41.  I'd also like to ensure that any desugaring that occurs propagates enough information into the MLIR that refactoring tools that want to run after type inference can do so.  For this, we need to be able to propagate type information up to the token stream, along with information about the kinds of expressions that contain the token.

**Comment by davidchisnall** [comment]
Imagine an infix operator such as `a add b`.  During canonicalisation, we'd turn this into `a.add(b)`.  A renamer, the simplest refactoring tool, needs to be able to identify both patterns in the source, but needs to run after type checking to ensure that it's only changing calls with types that match the renamed symbol rather than any other methods with the same name.  As long as we're able to identify that the `add` token in both cases is a call to the same method, that's fine.  I think with `apply` this can be somewhat more complex. For example, consider trying to rename an `apply` method to `do_the_thing`, you'd need to rewrite `a(i)` to `a.do_the_thing(i)`, so you'd need to track that the `(i)` corresponded to the `apply` call.  This kind of thing is fairly easy to do with the clang AST, where all of the type information is available in the AST.  As long as we can map type info back to AST nodes, it's probably easy to do for Verona too.

**Comment by rengolin** [comment]
Ah, I see, injective, not bijective. We don't need to convert the MLIR back into AST to match code, we only need the type info from MLIR and can do the rest in AST. That should be fine, I guess.

**Comment by rengolin** [comment]
#321 is implementing the first stage of the de-sugaring as a new ast pass. This will probably work for all others, too.

**Comment by rengolin** [comment]
This was a good discussion and now we have a more clear view on what to de-sugar where. From now on, specific de-sugaring will be tracked by their own issues.
