### ISSUE TITLE
Test infrastructure wishlist

### ISSUE THREAD

**Issue by plietar** [microsoft/verona#285]
The language test-suite is currently based on a bunch of cmake scripts that configure ctest. It is unstatisfying because it is inflexible and no one wants to write cmake code to extend it. As alternatives we've been considering switching to lit, or rewriting the cmake scripts into a more flexible (set of) python script. Please feel free to edit this post to add new items, or post them as a comment.

# Wishlist
- Configurable compiler invocation: different tests need to run the compiler in different modes, with different flags.
- Configurable expectations: some tests expect the compiler to return with a zero exit status, others with a non-zero one.
- Running multiple tools in sequence: For example we may want to compile a source file to bytecode, then execute this bytecode in the interpreter
- Pipe the result of one tool into the next: For example, feed to output of `verona-mlir` into itself, to make sure the IR is round-tripable.
- Compare the output to a golden file. "Output" may be many things: compiler stderr, IR output, internal data-structure, executed program's stdout/stderr.
- Compare the output with a set of inline FileCheck directives.

# Open questions
- Should tests be configured per-test or per-directory? The existing testsuite uses the following model: `$SUITE/$MODE/$TEST.verona`, where `$SUITE` allows tests to be grouped by feature (eg. name resolution), `$MODE` is how compiler flags / tool pipeline is configured (eg. compile-pass vs compile-fail).

- The test infrastructure is composed of test enumeration and test execution. Are we happy to keep the former entirely in CMake, while implementing the latter in Python? The cmake enumeration logic is essentialy "for $f in testsuite/*.verona; add_test(run_test.py $f); done".

**Comment by rengolin** [comment]
We had this internal discussion in January and in February @mjp41 updated the test harness in #396.
