### ISSUE TITLE
Shrink region trace meta-data

### ISSUE THREAD

**Issue by mjp41** [microsoft/verona#309]
Once #308 is merged, the traced region meta-data will be more than a 64 bytes.  There is a possibility to compact the data. Currently there are two fields for tracking size information:

https://github.com/microsoft/verona/blob/77c38324b816fd32c3cdbb0dbb812f7bcf02315c/src/rt/region/region_trace.h#L65-L69

As the address space is unlikely to go above 56bit for a long time, we can compact these into a single field that uses the top byte as the size after the previous compaction, and the the remaining 56bit as an accurate representation of the size.  If we need more space, we also know `snmalloc` will only allocate multiples of 16 bytes, and thus we get an extra 4 bits at the bottom of the representation. We can also play with the representation to use additional bits to get a more accurate previous size of the region.

**Comment by davidchisnall** [comment]
'64 pebibytes ought to be enough for anyone' - @mjp41
