### ISSUE TITLE
Running clangformat rule touches snmalloc

### ISSUE THREAD

**Issue by rengolin** [microsoft/verona#319]
For some reason, snmalloc is in `src/rt/external` instead of just `external` and that's messing with the clang format rule that globs `*.cc` and `*.h` inside `src`.

I don't see the problem in the CI, but when I run it on my machine, I get:
```
$ ninja clangformat
[1/1] cd /home/rengolin/devel/msrc/verona/build && /opt/clang-format-static/clang-format-9 -i /home/rengolin/devel/ms.../ubench.cc /home/rengolin/devel/msrc/verona/src/rt/test/systematic.h /home/rengolin/devel/msrc/verona/src/rt/verona.h
$ git diff
diff --git a/src/rt/external/snmalloc b/src/rt/external/snmalloc
--- a/src/rt/external/snmalloc
+++ b/src/rt/external/snmalloc
@@ -1 +1 @@
-Subproject commit 923705e514e850ee0070cef470fca9d9c47ca3da
+Subproject commit 923705e514e850ee0070cef470fca9d9c47ca3da-dirty
```

Which then I have to fix with:
```
$ git -C ../src/rt/external/snmalloc/ checkout .
Updated 1 path from the index
```

There are two ways to go about this and I'm not sure which one is best:
1. Move snmalloc to `external`, like the other submodules
2. Patch the `GLOB` expression to avoid `src/rt/external` (or any external) directories

**Comment by mjp41** [comment]
Can we use `git ls-files` to make it find all the file types in the repo, but not in any sub-repos?

**Comment by rengolin** [comment]
Hm, `git ls-files` generates a list of either `\n` or `\0` separated files, so I can't use it directly with `clang-format`. My CMake foo isn't good enough to understand how I can get a static list of files in a CMake variable not using `GLOB`.

**Comment by mjp41** [comment]
I'm trying at the moment
