### ISSUE TITLE
Implement BasicBlock arguments

### ISSUE THREAD

**Issue by rengolin** [microsoft/verona#322]
Earlier [prototype](https://github.com/rengolin/verona/commits/zzz/freevar) need to be extended to allow basic block arguments instead of `alloca/load/store` chains.

It could be done in the parser (since it's done in the AST), or it could be done in the generator (since it's only used for the initial MLIR lowering).

Any further transformation of the IR should handle arguments and reachability as usual.

**Comment by plietar** [comment]
What exactly do you mean by “free variable analysis”? Is it SSA construction, such as in https://pp.info.uni-karlsruhe.de/uploads/publikationen/braun13cc.pdf?

**Comment by mjp41** [comment]
I think we optimised/simplified the approach a little as we don't have arbitrary gotos.  The block structuring meant we could do this more simply:
https://github.com/microsoft/verona/blob/2b6916d3af6dbff8b73b6acb33b5b6fd8dfffade/src/compiler/ir/builder.h#L25-L32

This was really clean to implement, and worked very nicely.

**Comment by rengolin** [comment]
> I think we optimised/simplified the approach a little as we don't have arbitrary gotos. The block structuring meant we could do this more simply:

IIUC, you use something akin to type declaration (for pending types to be declared later), but here, with a pending PHI node.

The difference with MLIR is that we don't have phi nodes (they're basic block arguments) and we can't have pending basic blocks (we need to add instructions to them). 

In theory, what we have right now is "pending arguments", which could be updated every time we define/use a variable inside the block. But this creates too many useless arguments (MLIR can access SSA variables declared before, on dominating blocks) and "return values" as arguments to all blocks reached by the current one.

So, we either do like LLVM and run a pass that transforms all allocas into block arguments or we scan the AST for variables defined/used and use that information to directly create block arguments on creation.

The recursive algorithm to scan the AST I wrote earlier is simple (probably too simple), but it's also clean and only passes through each node once, saving information of the variables defined/used and creating snapshots at "entry-points" (ie. places where the MLIR generator will need block argument information).

I have not tested it in the generator yet, I was about to do that when priorities changed, but it should be simple to extend it.

I will read the paper @plietar suggested before continuing with this work. Hopefully it has a better way of doing it. I'll also look more in depth on the previous compiler for inspiration. Perhaps I'm not understanding completely your previous implementation and it is indeed simpler than either of my options.

**Comment by mjp41** [comment]
My comment is meant in addition to reading that paper.  I remember once we had implemented that paper we realised, we could simplify the implementation based on language assumptions.

I think working backwards as this paper does might fit particularly poorly with MLIR. 

@rengolin  Can you point me at your recusive algorithm?  I think I can see how to adapt this paper to work forwards due to the heavily structured nature of the language.  But it would need a liveness analysis on the AST.  Effectively the backwards construction in the paper is giving the liveness analysis as part of the construction.

**Comment by plietar** [comment]
FWIW, the old compiler, in which we implemented that paper, already uses block arguments rather than phi nodes.

Each BB has a list of parameters: https://github.com/microsoft/verona/blob/master/src/compiler/ir/ir.h#L304
And the terminators have a list of variables to pass onto the target: https://github.com/microsoft/verona/blob/master/src/compiler/ir/ir.h#L95

See for example: https://github.com/microsoft/verona/blob/master/testsuite/ir/compile-pass/loop/Main.test3.ir.txt BB1 has one argument, and the jump from BB0 and BB2 pass in a value.

The comments and variable names do mention “phi nodes”, because I was originally going to use phi nodes, but later found block arguments to be a nicer representation.

> we can't have pending basic blocks (we need to add instructions to them).

I don’t understand why not? A pending basic block is simply one for which more predecessors may be added later in the construction.

**Comment by mjp41** [comment]
I don't know how MLIR works well enough, but can we create an SSA value without a definition?  I have seen this done before with placeholder definitions, and then replacing the definition later, but that seems a little messy.  The original code did
```C++
fresh_variable(...)
```
which didn't need a definition, and then later would do
```C++
add_definition(...)
```
This separation makes it easy to work backwards, I am not sure there is an equivalent in MLIR.  But you guys would know better than me.

**Comment by rengolin** [comment]
> My comment is meant in addition to reading that paper.

I noticed when I got to the end of the comment block. :)

> @rengolin Can you point me at your recusive algorithm?

https://github.com/rengolin/verona/commits/zzz/freevar

> I think I can see how to adapt this paper to work forwards due to the heavily structured nature of the language. But it would need a liveness analysis on the AST. Effectively the backwards construction in the paper is giving the liveness analysis as part of the construction.

That's my current thinking, yes.

**Comment by rengolin** [comment]
> I don’t understand why not? A pending basic block is simply one for which more predecessors may be added later in the construction.

Nomenclature. I described a similar concept to yours in my reply and called it "pending arguments".

What I meant as "pending basic block" as pending construction (so not creating the block now, but doing so later when I know all the variables). If I did that, I wouldn't be able to continue construction of the block's operations.

With PHI nodes, it's easier to create a new opaque "verona.phi" for everything and then later find the endpoints and make it concrete with the values from all blocks it reach. But that was before I knew you used block arguments and not phi nodes. :)

I think we're mostly agreeing on the three existing strategies and their trade offs. I personally dislike creating allocas and cleaning them up immediately afterwards, and I think both of you do too, so it leaves us with only two viable options:
 * AST scan, construct blocks with full information straight away
 * pending arguments, update them as blocks are finished and all def/use places are known

If what I did in my branch is close enough, than it should be pretty simple to use it in MLIR.

**Comment by rengolin** [comment]
> I don't know how MLIR works well enough, but can we create an SSA value without a definition? I have seen this done before with placeholder definitions, and then replacing the definition later, but that seems a little messy. (...)
> 
> This separation makes it easy to work backwards, I am not sure there is an equivalent in MLIR. But you guys would know better than me.

Now that I (mostly) read the paper, it's just the GVN algorithm. 

The core idea of having opaque/incomplete instructions works fine in LLVM and MLIR, but you can't have an "opaque" basic block and then add operations to it. You can, however, add a zero-args block and then change the arguments, which is essentially the same thing.

This is what I tried to implement first. We already have part of the LVN implemented as our symbol table (we must extend to make that work), but the GVN part would have to keep back-tracking each variable declaration, and then remove unnecessary arguments in the end. This was my conclusion initially and seems to be what the paper prescribes.

The [new GVN algorithm](https://github.com/llvm/llvm-project/blob/master/llvm/lib/Transforms/Scalar/NewGVN.cpp) is even considerably more complex than I expect we need, mostly because it has to consider any crazy control flow that anyone can generate in IR, as well as the semantics of various IR constructs and the difference between values and operators, while we're very restricted to what the AST can produce and only care about value (I think).

I believe the AST has a much cleaner view of what we need, and we can create a single-pass list of all values in/out of blocks and use that info to add arguments to basic blocks and operands to branch instructions. Given that we have LVN for declared variables, a `lookup` will bring the correct value for the stack frame we're in on each block.

Note the keyword: "I believe". I haven't done that yet, so I can't be sure it will work. But I believe it should.

**Comment by rengolin** [comment]
@mjp41, I brought the patch forward to the current tree:
https://github.com/rengolin/verona/tree/mlir-freevar

As expected it doesn't account for the CFG. We may come up with a clever trick (like a `map<IR, Ast>`) when querying successors and predecessors in MLIR, but I haven't done that yet. If that doesn't work, then we'll probably have to re-implement the analysis in IR and rewrite the blocks' arguments.

**Comment by rengolin** [comment]
Ok, my take on it has the same problems as the simple approach as described in the paper (unnecessary arguments), so doesn't really help implementation-wise. At least in the paper we have a fix for that, so better if we just do it that way.

Parking the `mlir-freevar` branch into `zzz/freevar` again.

**Comment by rengolin** [comment]
WIP: https://github.com/rengolin/verona/tree/mlir-blockargs

**Comment by rengolin** [comment]
Ok, finished the main round of changes, commits in the branch above. It "works".

The generated IR seems to have tracked the right values to the right arguments on both conditionals and loops. Got rid of all allocas, fixed some type check problems (by adding casts to assign), but the code looks horrible and I still need to check the IR more closely on all examples to make sure we're not losing anything in the process.

Next steps:
 * Verify the IR generated and mark as golden (not to be changed by new refactory commits)
 * Identify all common idioms across functions and lift them into their own helper functions
 * clean up code, merge commits into logical blocks, submit PR.

**Comment by rengolin** [comment]
The MLIR lowering is changing drastically from a different input, which probably won't have such constructs.
