### ISSUE TITLE
Specs for the language

### ISSUE THREAD

**Issue by NickNaso** [microsoft/verona#37]
Hi everybody,
maybe this is not the right place to ask, but I want know where I can find the specifications for the programming language. Thank you.

**Comment by mjp41** [comment]
We have a lot of type rules and operational semantics, but they are not ready to share publicly yet.  The language is very much in-flux, so we don't want to polish the specification until it is more settled.

**Comment by NickNaso** [comment]
@mjp41 thank you for your quickly response.

**Comment by lnicola** [comment]
On a related note, are there any (academic, but not necessarily peer-reviewed) articles discussing the project? I skimmed the MSR site for a while, but couldn't find anything.

**Comment by mjp41** [comment]
@lnicola Not yet, we have some stuff in preparation.  But nothing ready to share yet.

**Comment by rengolin** [comment]
I've gathered the requirements to share documents to the public in #112. Even though that won't mean we'll share all of it at once (there's a lot of WIP documents that would actually be worse if shared in the current state), it defines how we'll share, when we do.
