### ISSUE TITLE
Trivial but curious: Why the name?

### ISSUE THREAD

**Issue by CodeOtter** [microsoft/verona#39]
https://en.m.wikipedia.org/wiki/Venona_project

It's very similar. Is Microsoft using Rust to out spies in hi-tech research labs? 😅

**Comment by mjp41** [comment]
It is common for Microsoft projects that are released without a final name to be "Project [CITYNAME]".  We have followed this convention.

And this project is all about "the owner".

**Comment by orcmid** [comment]
Oh.  I thought it was about the ubiquitous blend of Starbucks found everywhere on the Redmond campuses.
