### ISSUE TITLE
Verona runtime : is it a general language runtime or something solely for debugging?

### ISSUE THREAD

**Issue by JOE1994** [microsoft/verona#40]
First of all, thank you so much for making this project open-source 😄 .

I have a clarification question about the **verona** runtime : 

(from verona/docs/explore.md)

> With Project Verona, we are carving out an area of system programming, "infrastructure programming", that has important performance and predictability requirements, without needing raw access to the machine. 

I initially assumed that since Verona is a Rust-inspired language focusing on system programming, it would probably aim to have a minimal or no runtime.

Is the Verona runtime solely for debugging purposes, or is it something that is required to be running in the backend for all verona programs?

**Comment by plietar** [comment]
The interpreter is a stop-gap until an LLVM-based backend is implemented. We don't consider this part of the "Verona runtime".

However the rest of the runtime (ie. what's in `src/rt`) is here to stay. A lot of people tend to describe Rust and C as having no runtime, but effectively their memory allocator and threading libraries do form a runtime. The Verona runtime is closer to the C runtime than a JVM or .NET runtime.
