### ISSUE TITLE
Is there a release coming anytime soon?

### ISSUE THREAD

**Issue by wysisoft** [microsoft/verona#430]
It looks like this project has been going for 1.5 years without any releases, how long before there is a release so the community can compare its pros/cons to other languages?

**Comment by rengolin** [comment]
Verona is a research project into concurrent ownership for highly distributed programs and not a production language, so there are no plans for a release, per se. The repository is public so we can collaborate directly with anyone interested in the research we're doing, but currently, there is no expectation it will be in a shape for release any time soon.

We do, however, have strict rules about design (syntactic and semantic), validation and continuous integration, and runtime performance (including the memory allocator), which means it will be easy to move into production once it's in the right stage.

There are a number of binaries in the build that can test the different stages of compilation (ex. `verona-parser`, `verona-mlir`) and examples stress-testing the runtime (see `src/rt/test`), as well as older implementations (ex. `veronac`, `interpreter`) that help understand the progress in the project.

You can also read the multiple `MD` files in the project as well as check our [website](https://microsoft.github.io/verona/) for more information on the language, plans and design issues we're facing.
