### ISSUE TITLE
Nightly test failure after runtime update

### ISSUE THREAD

**Issue by rengolin** [microsoft/verona#436]
After merging #429, the [nightly test broke](https://dev.azure.com/ProjectVeronaCI/Project%20Verona/_build/results?buildId=2455&view=logs&j=b319cb12-f070-52ae-e2a6-04d190fd2bf4&t=6a2a3399-68cb-5009-63d6-a0475668c459&l=2606) with the following message:
```
         743/861 Test #810: runtime/func-sys-runtimepause_4_100 ..................................................Exit code 0xc0000409
         ***Exception:   4.72 sec
          D:/a/1/s/build/src/rt/RelWithDebInfo/func-sys-runtimepause.exe --cores 4 --seed 100 --seed_upper 103
         Seed: 1219900100
         Time so far: 1 seconds
         Seed: 1219900101
         Time so far: 2 seconds
         Seed: 1219900102
         Time so far: 3 seconds
         Seed: 1219900103
         Assertion failed: (external_event_sources > 0) || (running_thread == nullptr), file D:\a\1\s\src\rt\sched\threadpool.h, line 221
```
This is a new line in the PR, so highly likely created by it. 

There is [another failures in ASAN](https://dev.azure.com/ProjectVeronaCI/Project%20Verona/_build/results?buildId=2474&view=logs&j=9ba48eb9-f09c-51fd-259c-c1f9e917fe10&t=e02bd44e-db8b-5357-94a7-79c7308ada82&l=1648) on the same test that could be caused by the same issue:
```
==130387==ERROR: AddressSanitizer: FPE on unknown address 0x00000050883d (pc 0x00000050883d bp 0x7f4e4a4fbb90 sp 0x7f4e4a4fbac0 T2)
```

It's also possible that the line only caught what could already happen but now it's exposed by the new code.

**Comment by mjp41** [comment]
Fixed by #435
