### ISSUE TITLE
DSL for "Calibre Check"

### ISSUE THREAD

**Issue by prateekrastogi** [microsoft/verona#44]
Looking for ways to inject in Verona a DSL enabling concurrent neural network executions for:
https://github.com/jgraph/drawio/issues/715

**Comment by mjp41** [comment]
Verona is not at a stage where we can support this kind of scenario.  If you specify the requirements you would need for a DSL, then when we plan language features we will can consider those requirements.

**Comment by prateekrastogi** [comment]
My requirements is to support large-scale system bootstrap backpropagation through unfold and recurse, but with automatic concurrent integration of FFI for software dependencies with a system level DSL such as UML or json.
