### ISSUE TITLE
Unstable veronac test timing out

### ISSUE THREAD

**Issue by rengolin** [microsoft/verona#446]
The test `veronac/features/run-pass/integer.verona` is [failing randomly with timeout](https://dev.azure.com/ProjectVeronaCI/Project%20Verona/_build/results?buildId=2640&view=logs&j=e632f1d6-0a34-55c8-b58a-b7d0f9490cee&s=d654deb9-056d-50a2-1717-90c08683d50a&t=6eec3b4f-8232-50fe-9366-b417b07238a8&l=972) on MacOS.

Last time I've seen it happen was 8th April.

The build will be collected, so here's a snapshot of the error, for posterity
![image](https://user-images.githubusercontent.com/1040968/121499811-a053de00-c9d5-11eb-8f0d-99159fc5f8e7.png)

@plietar @sylvanc

**Comment by rengolin** [comment]
Just realised we had a similar issue (#77). If this happens again we'll disable the test like the others.

**Comment by Akaame** [comment]
Hello,

Is this a CI, MacOS or "solver" problem?

I have run this `veronac testsuite/veronac/features/run-pass/integer` on my Mac, however I was not able to reproduce the scenario described.

Could you give me some pointers on where to start investigating this?

Regards.

**Comment by rengolin** [comment]
Hi, I think this is a compiler issue. The old compiler may have some instability or memory corruption that only sometimes leads to an infinite loop.

Other tests had similar issues and were disabled, so I'm guessing this was a known issue back then, but never fixed.

I don't think it's worth looking out nto the underlying cause because this is an old code that won't be used any more and is here just for reference.

The new compiler is in `src/parser` and `src/mlir` but still not complete. The syntax and semantics are different on the new compiler, so looking at the old one won't help much in learning the language.

There are some new documents in `docs/internal` that you can look at, meanwhile.

**Comment by rengolin** [comment]
Old compiler tests are no longer executed after being moved to deprecated.
