### ISSUE TITLE
Building with MSVC 2019 needs EHSC option

### ISSUE THREAD

**Issue by trairia** [microsoft/verona#49]
My environments are follows:

OS: Windows 10 Pro x64
System Locale: Japanese (CP932)
Compiler: Visual Studio 2019 16.4.3

CMAKE_CXX_FLAGS includes "/WX" in MSVC environment. It cause some compilation issues.

## source and execution charset option 

In my environment (CP932 encoding), cl.exe needs "/utf-8" option to compile sources.

```
6>F:\project\verona\src\.\compiler/ir/ir.h(1,1): error C2220: the following warning is treated as an error
6>F:\project\verona\src\.\compiler/ir/ir.h(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (932). Save the file in Unicode format to prevent data loss
```

## "/EHsc" option

Exception handling needs "/EHsc" option.

```
8>F:\project\verona\external\CLI11\include\CLI/Option.hpp(674,1): error C2220: the following warning is treated as an error
8>F:\project\verona\external\CLI11\include\CLI/Option.hpp(674,1): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
8>Done building project "interpreter-sys-bin.vcxproj" -- FAILED.
```

CMake configure with `-DCMAKE_CXX_FLAGS="/EHsc /utf-8"` works fine for me.

**Comment by mjp41** [comment]
Thanks for reporting this. I have added UTF8, with #52.

I am surprised you are seeing `/EHsc` not set already.  That is set for me without any changes.

What version of CMake are you using?

**Comment by trairia** [comment]
I use CMake 3.16.1.

I had passed "/utf-8" option with -DCMAKE_CXX_FLAGS="/utf-8" to CMake.
So CMAKE_CXX_FLAGS were overwritten(/EHsc were deleted).
I pulled latest git HEAD. And it works fine.

**Comment by mjp41** [comment]
Great, thanks for letting me know.
