### ISSUE TITLE
Nim language

### ISSUE THREAD

**Issue by develooper1994** [microsoft/verona#54]
Have you ever heard of Nim language? It is also has a great c++ interface and Nim 1.0 came out recent time.

**Comment by BillGattes** [comment]
> Have you ever heard of Nim language? It is also has a great c++ interface and Nim 1.0 came out recent time.

And it's definitively better than C#, trust me I would know.

**Comment by mjp41** [comment]
Nim is a very interesting language.

There are many differences with what we are building. I think the main is the concept of ownership transfer.  As far as I understand Nim: each thread has a local heap, and the objects from this cannot be moved to another heap.  This allows for efficient memory management, but can make concurrent software hard to write.  In particular, it typically means you need to perform a [deep copy of data](https://nim-lang.github.io/Nim/manual_experimental.html#type-bound-operations-deepcopy).
The marshalling cost of the copy can be prohibitive. 

Ownership transfer allows for single access without the cost of copying. This has been the basis of messaging in Singularity, which was improved upon in Midori's C# (M#), and is also the basis of messaging in Pony.  This ownership transfer behaviour is also what is captured by Rust's Sync trait. In Verona, we are very much in that approach.

I look forward to seeing more developments in Nim.

**Comment by develooper1994** [comment]
I think Rust is overwhelming after long time of python usage. It would be very hard but I think you should consider python like easy to learn and use language(I know for big projects with python is terrible).
I am looking forward to interesting verona inventions.
