### ISSUE TITLE
Infrequent memory leak in func-con-external_event_source

### ISSUE THREAD

**Issue by mjp41** [microsoft/verona#552]
We are occassionally hitting a bug on this test:
https://dev.azure.com/ProjectVeronaCI/Project%20Verona/_build/results?buildId=3717&view=logs&j=b0abc04d-bfd5-55cd-41dd-470d60a21bba&t=0a299330-b715-5f5b-5b0e-8fa56ea0992f

We should enable better systematic testing on this, now it can cover external threads, to see if it is deterministically reproducible.

**Comment by rengolin** [comment]
Not sure it's the same, but another failure:
https://dev.azure.com/ProjectVeronaCI/Project%20Verona/_build/results?buildId=3719&view=logs&j=f4b67223-79ca-5175-3c9f-c4562941950d&t=b8a96312-7930-523f-d4be-447f9b386198&l=1670
```
         183/584 Test #175: runtime/func-con-external_event_source .................Exit code 0xc0000409
         ***Exception:   4.19 sec
         Harness starting.
          D:/a/1/s/build/src/rt/RelWithDebInfo/func-con-external_event_source.exe --seed 4005742088
         Seed: 4005742088
         debug_is_empty: found non-empty allocator
```

**Comment by rengolin** [comment]
Ah, yes, it seems to be exactly the same. Your original was:
```
 21/422 Test  #13: runtime/func-con-external_event_source ..........Exit code 0xc0000409
***Exception:  19.52 sec
Harness starting.
 D:/a/1/s/build/func-con-external_event_source.exe --seed 1558542514
Seed: 1558542514
debug_is_empty: found non-empty allocator
```

**Comment by rengolin** [comment]
[Another one](https://dev.azure.com/ProjectVeronaCI/Project%20Verona/_build/results?buildId=3747&view=logs&j=3fd1faa1-966d-5b52-1aab-243302a398db&t=f20d1b8c-4dae-528c-29e4-d139d825911b&l=1661):
```
         178/584 Test #175: runtime/func-con-external_event_source .................Exit code 0xc0000409
         ***Exception:   2.76 sec
         Harness starting.
          D:/a/1/s/build/src/rt/Release/func-con-external_event_source.exe --seed 3508332118
         Seed: 3508332118
         debug_is_empty: found non-empty allocator
```
