### ISSUE TITLE
Can Fibonacci be written like this? how to get when expression return value?

### ISSUE THREAD

**Issue by libin049** [microsoft/verona#569]
Can Fibonacci be written like this? how to get when expression return value?
```C++
fib(x: U64 & imm): cown[U64Obj] & imm
  {
    var pw = Promise.create();
    var pr = (mut-view pw).wait_handle();

    if (x < 2)
    {
      pw.fulfill(U64Obj.create(1));
    } 
    else
    {
      var pp1 = when () 
      {
        var p1 = Fib.fib(x - 1);
      };
      var pp2 = when () {
        var p2 = Fib.fib(x - 2);
      };
      when (pp1, pp2) {
        var r = U64Obj.create(pp1.v + pp2.v);
        pw.fulfill(r)
      };
    };
    pr
  }
```

**Comment by mjp41** [comment]
I haven't checked the syntax against the current interpreter, but that should work.

To get the value you would do something like

```
  var r = Fib.fib(9);
  when (r) {
      // do something with r.v
     f(r.v)
  }
```
Now this will run the function f with the value that the parallel computation has calculated.

**Comment by libin049** [comment]
> I haven't checked the syntax against the current interpreter, but that should work.
> 
> To get the value you would do something like
> 
> ```
>   var r = Fib.fib(9);
>   when (r) {
>       // do something with r.v
>      f(r.v)
>   }
> ```
> 
> Now this will run the function f with the value that the parallel computation has calculated.

thanks [mjp41](https://github.com/mjp41).  I want to concurrent execution Fib.fib(x - 1) and Fib.fib(x - 2), then get their result ,like this:
```C++
when () 
{
  p1 = Fib.fib(x - 1);
};
when () {
   p2 = Fib.fib(x - 2);
};
when (p1, p2) {
  var r = U64Obj.create(p1.v + p2.v);
  ...
};
```
I found it is hard to written.

**Comment by davidchisnall** [comment]
In the final syntax, this should end up looking something like:

```
p1 = when ()
{
  Fib.fib(x - 1);
};
p2 = when () {
   Fib.fib(x - 2);
};
when (p1, p2) {
  var r = U64(p1.v + p2.v);
  ...
};
```

We don't yet have an implementation that is at a state where we can write things like this yet.  Hopefully soon...

**Comment by mjp41** [comment]
So in the prototype, Promises are derived from cowns. This was to get things quickly working for a few examples.  We have a few ideas of making them a first class concept.  Either way we would intend them to be used in `when`.

**Comment by davidchisnall** [comment]
> I want to know, whether p1 and p2 types are promise[cown[U64Obj]&imm] above example? or p1 and p2 types are are cown[U64Obj]&imm ?

Specifically on this, you definitely won't have a `promise[cown[T]]` for something like this (unless you explicitly want to return a `cown[T]` from a promise.  It's still an open question whether `promise[T]` will be a subtype of `cown[T]`, or whether `promise[T]` and `cown[T]` will be subtypes of some `whenable[T]` (and, if so, whether that's an explicit thing in the type system).
