### ISSUE TITLE
what is the meaning of mut-view?

### ISSUE THREAD

**Issue by libin049** [microsoft/verona#571]
I found a lot of mut-view in example, but I donot found any explain about it. what is the meaning of mut-view?

e.g., in region101.verona
```   
// Create a little graph that has a cycle
    r1.field = r2;
    r2.field = r3;
    r3.field = mut-view(r1);
```

**Comment by mjp41** [comment]
`mut-view` is an artifact of the type system that was implemented in the prototype toolchain that @plietar built.  We have been redesigning the type system, and this should go away in the next implementation, when we have settled the details of the type system.

To answer your question, it is a way to convert an `iso` reference to a local `mut` reference.  This is something that we don't expect to be programmer visible, but as a way to get some stuff working was necessary.

**Comment by libin049** [comment]
thanks！

**Comment by libin049** [comment]
I got it, thanks!
