### ISSUE TITLE
Question about when expression scheduling

### ISSUE THREAD

**Issue by libin049** [microsoft/verona#573]
In the following example, why "task C0, x30 = 0"  output before "task B0, x20 = 1"? 
```C++
class Pingpong
{

  pingpong() {
      var BUFFER_NUM = 3;
      var x10 = cown.create(U64Obj.create(0));
      var x11 = cown.create(U64Obj.create(0));
      var x12 = cown.create(U64Obj.create(0));
      var x20 = cown.create(U64Obj.create(0));
      var x21 = cown.create(U64Obj.create(0));
      var x22 = cown.create(U64Obj.create(0));
      var x30 = cown.create(U64Obj.create(0));
      var x31 = cown.create(U64Obj.create(0));
      var x32 = cown.create(U64Obj.create(0));
      var i = 0;
      while(i<10) {
        var pingpong = i%BUFFER_NUM;
        if (pingpong == 0) {
          when(x10) {
             x10.v = x10.v+1;
             Builtin.print2("task A{}, x10 = {}\n", i, x10.v);
          };
          when(x10, x20) {
                x20.v = x10.v;
                Builtin.print2("task B{}, x20 = {}\n", i, x20.v);
          };
          when(x20, x30) {
             x30.v = x20.v;
             Builtin.print2("task C{}, x30 = {}\n", i, x30.v);
          };
        };
        if (pingpong == 1) {
          when(x11) {
             x11.v = x11.v+1;
             Builtin.print2("task A{}, x11 = {}\n", i, x11.v);
          };
          when(x11, x21) {
                x21.v = x11.v;
                Builtin.print2("task B{}, x21 = {}\n", i, x21.v);
          };
          when(x21, x31) {
             x31.v = x21.v;
             Builtin.print2("task C{}, x31 = {}\n", i, x31.v);
          };
        };
        if (pingpong == 2) {
          when(x12) {
             x12.v = x12.v+1;
             Builtin.print2("task A{}, x12 = {}\n", i, x12.v);
          };
          when(x12, x22) {
                x22.v = x12.v;
                Builtin.print2("task B{}, x21 = {}\n", i, x22.v);
          };
          when(x22, x32) {
             x32.v = x22.v;
             Builtin.print2("task C{}, x32 = {}\n", i, x32.v);
          };
        };
        i=i+1;
      };
  }
}


class Main
{
  main()
  {
    Pingpong.pingpong();
  }
}
```
![image](https://user-images.githubusercontent.com/7247717/164599430-38a78a1f-5580-4584-8b84-d5c84d01dde0.png)

**Comment by mjp41** [comment]
So this is an area, we have been actively changing.  I think looking at your trace you are running with a checkout before the AcquireAll semantics became the default.  We changed because 

- We found that the AcquireOne semantics was confusing.  Your issue is exactly that confusion
- Two found an efficient way to implement it.

I think if you pull in #553 then the semantics are much more intuitive.

I am happy to expand more.  Also, we have a paper under submission on this, which I can share with you. (I don't want to post directly, as the review process is double blind, and I don't want to invalidate the anonymity.)

**Comment by libin049** [comment]
Thank [mjp41](https://github.com/mjp41). For the paper,  If it is convenient for you, could you send it to my email hsslb049@gmail.com?

**Comment by libin049** [comment]
@mjp41  When will your paper be published. I'm very interested of it.  I feel verona concurrency model is very similar to openMP task dependency model. It is powerful than any concurrency model I know.

**Comment by mjp41** [comment]
@libin049 sorry I completely forgot to send you our draft. I have now done that.

We still have about a month before we will here if it is accepted.

**Comment by libin049** [comment]
Got it! Thank you @mjp41 !
