### ISSUE TITLE
verona-mlir do not support cown, when

### ISSUE THREAD

**Issue by libin049** [microsoft/verona#585]
It seems that verona-mlir do not support cown, when, iso, mut and so on; only deprecated veronac support that,  is it right?
```C++
var c1 = cown.create(U64Obj.create(1));
when(c1) {
  
};
```
![image](https://user-images.githubusercontent.com/7247717/166107620-0e042b7d-7890-4084-b52f-fcc33a8c885c.png)

**Comment by rengolin** [comment]
Correct. The `verona-mlir` doesn't support most language features. The deprecated `veronac` supports an old spec of the language that is no longer what we're working with, and to an extent, so does `verona-mlir`. Both exposed issues in the design which we're working on to fix, and will be available on the next iteration of `verona-mlir` and hopefully, fix all semantics issues.

Also, please note that the `verona-mlir` is not the actual compiler, and is just a tool that we use to convert Verona code into MLIR / LLVM IR. The final compiler will have a lot more logic to include Verona files, know where the runtime libraries are, generate IR, link all together with the C++ libraries and create actual executables.

But it will use the same libraries that the `verona-mlir` tool uses, in the same way LLVM's tools like `lli`, `llc`, etc use the same libraries as `clang`, but only do part of the story.
