### ISSUE TITLE
Why not use a more C/C++ like syntax?

### ISSUE THREAD

**Issue by MarcusJohnson91** [microsoft/verona#599]
The main problem rust faces is it's unfamiliar syntax

**Comment by mjp41** [comment]
The current iterations we are working on I closer syntactically to C++.  I would say we are drawing a lot from both C++ and TypeScript at the moment. 

Most of the development is currently blocked on some theory around the type system we have been working on, so we haven't been pushing the syntax more until we have those solved.

**Comment by vpopescu** [comment]
Personally I don't agree with the OP, I don't think it's the syntax, I'd rather see the team focus on removing language noise, which makes rust hard on the eyes.  I have an especial dislike for the lifetime syntax ('a).

There are plenty of languages out there that have "unfamiliar" syntax if you have a C/C++ bias. F#, Ruby, Python, Scala...
