### ISSUE TITLE
verona develop progress , any compare with google carbon language.

### ISSUE THREAD

**Issue by cnmade** [microsoft/verona#604]
google now release their carbon language, a compiled langauge, mostly like cpp/rust.
Is verona still being developed?

any release GA date?

or why not join together to develop a new language. 
I see carbon has more active develop progress.

**Comment by elazarl** [comment]
@cnmade the goals of the languages are very different.

Carbon empasizes C++ compatability, and rejects mandatory lifetime checking to be C++ compatible

Verona seeks other static analysis methods to be more ergonomic than Rust's borrow checker, but still as safe.

**Comment by cnmade** [comment]
thanks for explain.
