### ISSUE TITLE
The CLA Bot hasn't been added to this repo

### ISSUE THREAD

**Issue by tfolbrecht** [microsoft/verona#65]
The bot to check if contributors have signed the Microsoft Contributor License Agreement isn't configured on this repo. 

Happy hacking!

**Comment by mjp41** [comment]
I can see a check for #64, and it has requested CLAs from a bunch of PRs so far.  It may have decided #64 doesn't require a CLA signing as it is sufficiently small change.

**Comment by tfolbrecht** [comment]
My mistake!
