### ISSUE TITLE
Type system implementation work

### ISSUE THREAD

**Issue by mjp41** [microsoft/verona#8]
This issue contains the WIP gaps for the type system.  There are several aspects of the formalisation that have not been implemented.  This issues is intended to track the main omissions in the implementation:

- [ ] Checking same region for certain operations.  For instance, assignment to `mut` fields, should ensure the regions are the same, this is not currently enforced.
- [ ] Invalidating regions on updates.  Certain operations mean we must invalidate variables accessing certain regions.  For instance, assignment to a `iso` field, must invalidate references to sub-regions, and  calls to `trace` must invalidate references into the traced region, and sub-regions.
  This invalidation also need to be expressed at the function signature level.
- [ ] Subtyping for interfaces with generic methods
- [ ] Implementation of `readonly` capability.
- [ ] Restrict types of finaliser to not allow mutation of the existing structure (requires read-only).
- [ ] Inferring `mut-view`: certain borrowing like operations are implicit, but not all. Currently, we require the programmer to insert `mut-view` in many places to handle the lack of inference of capability coercions.

**Comment by RobJellinghaus** [comment]
Could there be a separate issue tracking open issues in the formalization?  Juxtaposing this issue and that issue would be incredibly useful for tracking the state of the overall project.

**Comment by RobJellinghaus** [comment]
Also will the formalization itself be checked into this repository?

**Comment by NickNaso** [comment]
Myabe use the tag system could be helpful to differentiate the issues.

**Comment by mjp41** [comment]
@RobJellinghaus We are still trying to work out the best way to get the formalisation details out.  The Ph.D. students involved need peer reviewed papers, so we don't want to do anything to damage being able to get those, but also having the details here would be highly beneficial.

@NickNaso we will move the tag system as things develop.

**Comment by RobJellinghaus** [comment]
Ah I see.  Are you formalizing using a proof assistant or other mechanized methodology?  Or are the proofs going to be paper proofs?  My assumption was the former, hence my asking about checking in those proof artifacts.  If you're not going to be mechanizing the proof, my question makes less sense.

**Comment by mjp41** [comment]
@RobJellinghaus So @plietar has been doing a small amount of mechanized formalisation, but it is mostly paper definitions and proofs at the moment.
