### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by Yuhanun** [microsoft/verona#89]
Hello,

is there any timeline available for the language?

**Comment by mjp41** [comment]
No, we are still heavily in the research stage.  We will add more concrete details as we complete the research.

**Comment by Yuhanun** [comment]
Okay, thank you!

**Comment by rengolin** [comment]
I'm adding projects for issues, which won't have timelines per se, but could give an idea of progress and what's left to do. Hope this helps.
